export const MODEL = {
  name: 'TheBiasGraph',
  tagline: 'TheBiasGraph · custom neural network · trained on comparison bias · 10,000+ hours of content',
  shortTagline: 'Trained on 10,000+ hours of comparison bias',
  stats: {
    hours: 10247,
    articlesCompared: 1_200_000,
    storyClusters: 142_900,
    dimensions: 8,
    humanAgreement: 0.946,
    outletsCovered: 312,
    paramCount: '139M',
    studentParamCount: '67M',
    gpuHours: 88,
    encoderLayers: 12,
    attentionHeads: 12,
    hiddenDim: 768,
  },
  version: 'v3.0.0',
  trainedOn: '2026-01-22',
  linkedinUrl: 'https://linkedin.com/in/REPLACE_ME',
} as const
